"""Runtime parameters for URDF Ops keypoint observation contracts."""

from __future__ import annotations

URDF_OPS_KEYPOINT_OBSERVATION_SCHEMA_VERSION = "urdf-ops.keypoint-observations.v1"

KEYPOINT_OBSERVATION_DEFAULT_FRAME_ID = "world"
KEYPOINT_OBSERVATION_MAX_BATCH_FRAMES = 50_000
KEYPOINT_OBSERVATION_MAX_LABEL_LENGTH = 96
KEYPOINT_OBSERVATION_MAX_LINK_NAME_LENGTH = 160
KEYPOINT_OBSERVATION_MAX_FRAME_ID_LENGTH = 128
KEYPOINT_OBSERVATION_MAX_CAMERA_NAME_LENGTH = 128
KEYPOINT_OBSERVATION_MAX_DATASET_REPO_LENGTH = 256
KEYPOINT_OBSERVATION_MAX_DATASET_REVISION_LENGTH = 128
KEYPOINT_OBSERVATION_MAX_ROBOT_ID_LENGTH = 128
KEYPOINT_OBSERVATION_MIN_CONFIDENCE = 0.0
KEYPOINT_OBSERVATION_MAX_CONFIDENCE = 1.0
KEYPOINT_OBSERVATION_READY_MIN_POSITION_KEYPOINTS = 1
