from __future__ import annotations

from typing import Final


TRAINING_CLOUD_CONTROL_INLINE_PAYLOAD_MAX_BYTES: Final = 1_000_000
TRAINING_CLOUD_CONTROL_PAYLOAD_FORMAT: Final = "json"
TRAINING_CLOUD_CONTROL_EXECUTOR_TYPE: Final = "urdfops-cloud"
TRAINING_CLOUD_CONTROL_REDACTION_PLACEHOLDER: Final = "REDACTED_SECRET"
TRAINING_CLOUD_CONTROL_SECRET_MIN_REDACTION_CHARS: Final = 4
